# Generated by Django 3.2.18 on 2023-03-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='url',
            new_name='Write',
        ),
    ]
